blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.formulario, name='formulario'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('gracias/', views.gracias, name='gracias'),
]

vivo_unach/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('resultados/', admin.site.urls),
    path('', include('blog.urls')),

]

blog/models.py
from django.db import models
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import MaxValueValidator, MinValueValidator

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Formulario(models.Model):
    rut = models.CharField(max_length=9, help_text="Tu RUT sin puntos ni guion")
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    nrofono = PhoneNumberField(help_text="Los 8 dígitos luego del +569", default='9')
    email = models.EmailField()

    """Ciudades"""
    ARICA = 'ARICA'
    IQUIQUE = 'IQUIQUE'
    CALAMA = 'CALAMA'
    ANTOFAGASTA = 'ANTOFAGASTA'
    COPIAPO = 'COPIAPO'
    LASERENA = 'LASERENA'
    QUILPUE = 'QUILPUE'
    SANTIAGO = 'SANTIAGO'
    MOLINA = 'MOLINA'
    TALCA = 'TALCA'
    CHILLAN = 'CHILLAN'
    LOTA = 'LOTA'
    TALCAHUANO = 'TALCAHUANO'
    CONCEPCION = 'CONCEPCION'
    LOSANGELES = 'LOSANGELES'
    ANGOL = 'ANGOL'
    TEMUCO = 'TEMUCO'
    PITRUFQUEN = 'PITRUFQUEN'
    VILLARRICA = 'VILLARRICA'
    VALDIVIA = 'VALDIVIA'
    PUNTAARENAS = 'PUNTAARENAS'
    LINARES = 'LINARES'
    PARRAL = 'PARRAL'
    NINHUE = 'NINHUE'
    QUIRIHUE = 'QUIRIHUE'
    CHILLANVIEJO = 'CHILLANVIEJO'
    BULNES = 'BULNES'
    SANCARLOS = 'SANCARLOS'
    SANIGNACIO = 'SANIGNACIO'
    ELCARMEN = 'ELCARMEN'
    SANNICOLAS = 'SANNICOLAS'
    PINTO = 'PINTO'
    COIHUECO = 'COIHUECO'
    ÑIQUEN = 'ÑIQUEN'
    QUILLON = 'QUILLON'
    YUNGAY = 'YUNGAY'

    CIUDAD_CHOICES = (
        ('', 'Escoge una ciudad...'),
        (ARICA, 'Arica'),
        (IQUIQUE, 'Iquique'),
        (CALAMA, 'Calama'),
        (ANTOFAGASTA, 'Antofagasta'),
        (COPIAPO, 'Copiapó'),
        (LASERENA, 'La Serena'),
        (QUILPUE, 'Quilpué'),
        (SANTIAGO, 'Santiago'),
        (MOLINA, 'Molina'),
        (TALCA, 'Talca'),
        (CHILLAN, 'Chillán'),
        (LOTA, 'Lota'),
        (TALCAHUANO, 'Talcahuano'),
        (CONCEPCION, 'Concepción'),
        (LOSANGELES, 'Los Ángeles'),
        (ANGOL, 'Angol'),
        (TEMUCO, 'Temuco'),
        (PITRUFQUEN, 'Pitrufquén'),
        (VILLARRICA, 'Villarrica'),
        (VALDIVIA, 'Valdivia'),
        (PUNTAARENAS, 'Punta Arenas'),
        (LINARES, 'Linares'),
        (PARRAL, 'Parral'),
        (NINHUE, 'Ninhue'),
        (QUIRIHUE, 'Quirihue'),
        (CHILLANVIEJO, 'Chillán Viejo'),
        (BULNES, 'Bulnes'),
        (SANCARLOS, 'San Carlos'),
        (SANIGNACIO, 'San Ignacio'),
        (ELCARMEN, 'El Carmen'),
        (SANNICOLAS, 'San Nicolás'),
        (PINTO, 'Pinto'),
        (COIHUECO, 'Coihueco'),
        (ÑIQUEN, 'Ñiquén'),
        (QUILLON, 'Quillón'),
        (YUNGAY, 'Yungay'),
    )
    ciudad = models.CharField(max_length=20, choices=CIUDAD_CHOICES)
    PRIMERO = 'PRIMERO'
    SEGUNDO = 'SEGUNDO'
    TERCERO = 'TERCERO'
    CUARTO = 'CUARTO'
    OTRO = 'OTRO'
    ANIO_POSTULANTE_CHOICES = (
        ('', 'Escoge un curso...'),
        (PRIMERO, '1° medio'),
        (SEGUNDO, '2° medio'),
        (TERCERO, '3° medio'),
        (CUARTO, '4° medio'),
        (OTRO, 'Ya egresé'),
    )
    anioegreso = models.CharField(max_length=4, blank=True)
    aniopost = models.CharField(max_length=15, choices=ANIO_POSTULANTE_CHOICES)
    """anioegreso = models.SmallIntegerField(
        default=2015,
        blank=True,
        validators=[
            MinValueValidator(2000),
            MaxValueValidator(3000)
    ]
    )"""
    """ColegiosAdventistas"""
    COADAR = 'Arica'
    CAI = 'Iquique'
    CADECAL = 'Calama'
    COADAN = 'Antofagasta'
    CADECOP = 'Copiapó'
    CADELSE = 'La Serena'
    CADEQUI = 'Quilpué'
    CABU = 'Buenaventura'
    CAP = 'Porvenir'
    COALC = 'La Cisterna'
    CALC = 'Las Condes'
    CASAN = 'Santiago Norte'
    CASS = 'Santiago Sur'
    CASAP = 'Santiago Poniente'
    CAM = 'Molina'
    COADET = 'Talca'
    CACH = 'Chillan'
    CAL = 'Lota'
    CATCE = 'Talcahuano Centro'
    CADET = 'Talcahuano'
    CADEC = 'Concepción'
    CEALA = 'Los Angeles'
    COADVAN = 'Angol'
    COADTE = 'Temuco'
    COADPI = 'Pitrufquén'
    CADVI = 'Villarrica'
    CADVA = 'Valdivia'
    COADPA = 'Punta Arenas'
    COLEGIOS_ADV_CHOICES = (
        ('', 'Escoge un colegio...'),
        (COADAR, 'Colegio Adventista de Arica'),
        (CAI, 'Colegio Adventista de Iquique'),
        (CADECAL, 'Colegio Adventista de Calama'),
        (COADAN, 'Colegio Adventista de Antofagasta'),
        (CADECOP, 'Colegio Adventista de Copiapó'),
        (CADELSE, 'Colegio Adventista de La Serena'),
        (CADEQUI, 'Colegio Adventista de Quilpué'),
        (CABU, 'Colegio Adventista de Buenaventura'),
        (CAP, 'Colegio Adventista Porvenir'),
        (COALC, 'Colegio Adventista La Cisterna'),
        (CALC, 'Colegio Adventista Las Condes'),
        (CASAN, 'Colegio Adventista Santiago Norte'),
        (CASS, 'Colegio Adventista Santiago Sur'),
        (CASAP, 'Colegio Adventista Santiago Poniente'),
        (CAM, 'Colegio Adventista de Molina'),
        (COADET, 'Colegio Adventista de Talca'),
        (CACH, 'Colegio Adventista de Chile'),
        (CAL, 'Colegio Adventista de Lota'),
        (CATCE, 'Colegio Adventista Talcahuano Centro'),
        (CADET, 'Colegio Adventista de Talcahuano'),
        (CADEC, 'Colegio Adventista de Concepción'),
        (CEALA, 'Centro Educacional Adventista Los Angeles'),
        (COADVAN, 'Colegio Adventista de Angol'),
        (COADTE, 'Colegio Adventista de Temuco'),
        (COADPI, 'Colegio Adventista de Pitrufquén'),
        (CADVI, 'Colegio Adventista de Villarrica'),
        (CADVA, 'Colegio Adventista de Valdivia'),
        (COADPA, 'Colegio Adventista de Punta Arenas'),
    )
    colegioadv = models.CharField(max_length=40, choices=COLEGIOS_ADV_CHOICES, blank=True)
    """Colegios"""
    SANVICENTE = 'Colegio San Vicente de Paul'
    PURISIMA = 'Colegio Purísima Concepción'
    SANBUENA = 'Colegio San Buenaventura'
    SANESTEB = 'Colegio San Esteban'
    CHILLAN = 'Colegio Chillán'
    CREACION = 'Colegio Creación'
    BICENTEP = 'Liceo Bicentenario E.P.'
    SAGRADOCOR = 'Colegio Sagrado Corazón de J.'
    CESB = 'CESB-Colegio Tecnico Profesional P. Enrique'
    SYDNEY = 'Colegio Sydney College'
    DARIOSAL = 'Colegio Tecnológico Darío Salas'
    DAVINCI = 'Colegio Da Vinci'
    SANFERNANDO = 'Colegio San Fernando'
    DINABEC = 'Dinabec College'
    SANAGUST = 'Colegio San Agustín'
    POLIVPHURT = 'C. Polivalente Padre A. Hurtado'
    ALCAZARES = 'Colegio Alcázares de Ñuble'
    LICNARCISO = 'Liceo Narciso Tondreau'
    DIEGOPORT = 'Liceo Diego Portales Palazuelos'
    CIUDADEDUC = 'Colegio Ciudad Educativa'
    MARTABRUNET = 'Liceo Bicentenario Marta Brunet'
    COMEWEALTH = 'Comewealth School'
    FRANCISOASIS = 'Colegio Francisco de Asis'
    JORGEALESSANDRI = 'Liceo Jorge Alessandri Rodríguez'
    POLIVCARLOS = 'Liceo Polivalente Carlos Montane C.'
    POLIVJUVENAL = 'Liceo Polivalente Juvenal Hernández Jaque'
    COYAM = 'Colegio Coyam'
    INSUCO = 'INSUCO- Instituto Superior de Comercio Insuco'
    ARTPRAT = 'Liceo Arturo Prat Chacón'
    SANTACRUZLARQUI = 'Liceo Santa Cruz de Larqui'
    A17YUNGAY = 'Liceo A-17 Yungay'
    POLITJOSEMANUEL = 'Liceo Politécnico José Manuel P.'
    PUENTENUBLE = 'Liceo Técnico Puente Ñuble'
    DARIOSALAS = 'Colegio Polivalente Darío Salas'
    CHILLANA8 = 'Liceo Agrícola de Chillán A-8'
    PUEBLOSECO = 'Liceo Pueblo Seco'
    POLITCIGN = 'Liceo Politécnico C. Ignacio C.'
    SENORACARMEN = 'Colegio Nuestra Señora del Carmen'
    CLAUDIOARRAU = 'Liceo Claudio Arrau Leon'
    MABELCONDEMARIN = 'Liceo Técnico Mabel Condemarín'
    ALTAZOR = 'Colegio Altazor'
    YIRE = 'Liceo Politécnico Yiré'
    HISPANRIOVIEJO = 'Colegio Hispanoamericano Río Viejo'
    INTECH = 'Intech'
    ARBOLVIDA = 'Colegio El Árbol de la Vida'
    REPUBITALIA = 'Liceo República de Italia'
    ARAUCANA = 'Centro de Estudios la Araucana'
    SENORAMERCED = 'Liceo Nuestra Señora de la Merced'
    SEBASTIANSCHOOL = 'Sebastian School'
    ARTUROPACHECO = 'Liceo Arturo Pacheco Altamirano'
    COLEGIOCONCE = 'Colegio Concepción'
    COLCHOLGUAN = 'Colegio Cholguán'
    INSTSANTMARIA = 'Instituto Santa María'
    SANTTERESALOSANDES = 'Colegio Santa Teresa de los Andes'
    SEMINALBERTOHURT = 'Colegio Seminario Padre Alberto Hurtado'
    COLEGIOS_CHOICES = (
        ('', 'Escoge un colegio...'),
        (SANVICENTE, 'Colegio San Vicente de Paul'),
        (PURISIMA, 'Colegio Purísima Concepción'),
        (SANBUENA, 'Colegio San Buenaventura'),
        (SANESTEB, 'Colegio San Esteban'),
        (CHILLAN, 'Colegio Chillán'),
        (CREACION, 'Colegio Creación'),
        (BICENTEP, 'Liceo Bicentenario E.P.'),
        (SAGRADOCOR, 'Colegio Sagrado Corazón de J.'),
        (CESB, 'CESB-Colegio Tecnico Profesional P. Enrique'),
        (SYDNEY, 'Colegio Sydney College'),
        (DARIOSAL, 'Colegio Tecnológico Darío Salas'),
        (DAVINCI, 'Colegio Da Vinci'),
        (SANFERNANDO, 'Colegio San Fernando'),
        (DINABEC, 'Dinabec College'),
        (SANAGUST, 'Colegio San Agustín'),
        (POLIVPHURT, 'C. Polivalente Padre A. Hurtado'),
        (ALCAZARES, 'Colegio Alcázares de Ñuble'),
        (LICNARCISO, 'Liceo Narciso Tondreau'),
        (DIEGOPORT, 'Liceo Diego Portales Palazuelos'),
        (CIUDADEDUC, 'Colegio Ciudad Educativa'),
        (MARTABRUNET, 'Liceo Bicentenario Marta Brunet'),
        (COMEWEALTH, 'Comewealth School'),
        (FRANCISOASIS, 'Colegio Francisco de Asis'),
        (JORGEALESSANDRI, 'Liceo Jorge Alessandri Rodríguez'),
        (POLIVCARLOS, 'Liceo Polivalente Carlos Montane C.'),

blog/forms.py
from django import forms
from .models import Post, Formulario
"""from phonenumber_field.formfields import PhoneNumberField"""


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)


class Form(forms.ModelForm):
    class Meta:
        model = Formulario

        fields = (
            'rut',
            'nombres',
            'apellidos',
            'nrofono',
            'email',
            'colegio',
            'ciudad',
            'colegioadv',
            'aniopost',
            'anioegreso',
            'carrera_post_1',
            'carrera_post_2',
            'carrera_post_3',
        )
        labels = {
            'rut': 'RUT',
            'nombres': 'Nombres',
            'apellidos': 'Apellidos',
            'nrofono': 'Número Telefónico',
            'email': 'Correo',
            'colegio': 'Colegio',
            'ciudad': 'Ciudad',
            'colegioadv': 'Colegio Adventista',
            'aniopost': 'Curso',
            'anioegreso': 'Año de Egreso',
            'carrera_post_1': 'Opción 1',
            'carrera_post_2': 'Opción 2',
            'carrera_post_3': 'Opción 3',
        }

        widgets = {
            'rut': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'XXXXXXXXX'}),
            'nombres': forms.TextInput(attrs={'class': 'form-control'}),
            'apellidos': forms.TextInput(attrs={'class': 'form-control'}),
            'nrofono': forms.TextInput(attrs={'placeholder': '9XXXXXXXX'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'colegio': forms.Select(attrs={'class': 'form-control'}),
            'ciudad': forms.Select(attrs={'class': 'form-control'}),
            'colegioadv': forms.Select(attrs={'class': 'form-control'}),
            'aniopost': forms.Select(attrs={'class': 'form-control'}),
            'anioegreso': forms.NumberInput(attrs={'class': 'form-control', 'style': 'width:10ch'}),
            'carrera_post_1': forms.Select(attrs={'class': 'form-control'}),
            'carrera_post_2': forms.Select(attrs={'class': 'form-control'}),
            'carrera_post_3': forms.Select(attrs={'class': 'form-control'}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post
from .forms import PostForm, Form
from django.contrib.auth.decorators import login_required


@login_required
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


def formulario(request):
    if request.method == "POST":
        form = Form(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.save()
            return redirect('gracias')
    else:
        form = Form()
    return render(request, 'blog/formulario.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


def gracias(request):
    return render(request, 'blog/gracias.html', {})

blog/templates/blog/base.html
{% load static %}

<html>
    <head>
        <title>Vivo UnACh</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <div class="container-2">
        <div class="col-xs-1 col-sm-2 col-md-4">
            <img src="{% static 'images/logounach2.png' %}">
        </div>
        </div>
    <div class="container">
            {% block content %}
            {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock %}

</body>
</html>

blog/templates/blog/formulario.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="ingresa">
        <h3>Ingresa tus datos</h3>
    </div>
    <form method="POST" class="post-form">
    {% csrf_token %}
        <div class="col-xs-1 col-sm-10 col-md-8 col-lg-10 col-lg-offset-8">
            {{ form.rut|as_crispy_field }}
        </div>
        <div class="col-xs-1 col-sm-10 col-md-8 col-lg-10">
            {{ form.nombres|as_crispy_field }}
        </div>
        <div class="col-xs-1 col-sm-10 col-md-8 col-lg-10">
            {{ form.apellidos|as_crispy_field }}
        </div>
        <div class="col-xs-1 col-sm-10 col-md-7">
            {{ form.nrofono|as_crispy_field }}
        </div>
        <div class="col-xs-1 col-sm-10 col-md-8 col-lg-10">
            {{ form.email|as_crispy_field }}
        </div>
        <div class="col-xs-1 col-sm-10 col-md-8 col-lg-10">
            {{ form.ciudad|as_crispy_field }}
        </div>
    <h4>¿Perteneces a un Colegio Adventista?</h4>
    <div class="btn-group btn-group-toggle" data-toggle="buttons">
        <label class="btn btn-info">
            <button type="button" class="btn btn-info" id="adv" onclick="mostraradv()">Sí</button>
        </label>
        <label class="btn btn-info">
            <button type="button" class="btn btn-info" id="noadv" onclick="mostrarcol()">No</button>
        </label>
    </div>
        <div id="colegio_advdiv_id" class="col-xs-1 col-sm-10 col-md-8 col-lg-10" style="display: none">
            {{ form.colegioadv|as_crispy_field }}
        </div>
        <div id="colegio_id" class="col-xs-1 col-sm-10 col-md-8 col-lg-10" style="display: none">
            {{ form.colegio|as_crispy_field }}
        </div>
        <div id="aniopostulante" class="col-xs-1 col-sm-10 col-md-8 col-lg-10">
            {{ form.aniopost|as_crispy_field }}
        </div>
        <!-- Comienza escondido el div que contiene al año de egreso -->
        <div id="anioegresopostdiv_id" class="col-xs-1 col-sm-10 col-md-8 col-lg-10" style="display: none;">
            {{ form.anioegreso|as_crispy_field }}
        </div>
        <h4>Carreras de Interés</h4>
        <div class="col-xs-1 col-sm-10 col-md-8 col-lg-10">
            {{ form.carrera_post_1|as_crispy_field }}
        </div>
        <div class="col-xs-1 col-sm-10 col-md-8 col-lg-10">
            {{ form.carrera_post_2|as_crispy_field }}
        </div>
        <button type="submit" class="save btn btn-info btn-lg">Enviar</button>
    </form>
{% endblock %}

{% block scripts %}
<script>

    const ID_SELECTOR_ANIOPOST = "#id_aniopost";
    const ID_DIV_ANIOEGRESO = "#anioegresopostdiv_id";
    const OPTION_VALUE_COMPARE = "OTRO"; // Igual sería bueno darle un nombre más representativo a esta opción

    $(document).ready(function() {
        /* ¿Cual es el campo selector?
        es aniopostulante
        El #aniopostulante es el identificador del div que encapsula al campo de entrada selector que tiene
        id #id_aniopost
        */

        // Escuchando evento change en selector de aniopost
        $(document).on("change", ID_SELECTOR_ANIOPOST, function (evt) {
            let optionValue = $(this).val();
            if (optionValue === OPTION_VALUE_COMPARE) {
                $(ID_DIV_ANIOEGRESO).show();
            } else {
                $(ID_DIV_ANIOEGRESO).hide();
            }
        });
    });

    function mostraradv(){
        document.getElementById("colegio_advdiv_id").style.display = "block";
        document.getElementById("colegio_id").style.display = "none";
    }
    function mostrarcol(){
        document.getElementById("colegio_id").style.display = "block";
        document.getElementById("colegio_advdiv_id").style.display = "none";
    }
    function checkRut(rut) {
    // Despejar Puntos
    var valor = rut.value.replace('.','');
    // Despejar Guión
    valor = valor.replace('-','');

    // Aislar Cuerpo y Dígito Verificador
    cuerpo = valor.slice(0,-1);
    dv = valor.slice(-1).toUpperCase();

    // Formatear RUN
    rut.value = cuerpo + '-'+ dv

    // Si no cumple con el mínimo ej. (n.nnn.nnn)
    if(cuerpo.length < 7) { rut.setCustomValidity("RUT Incompleto"); return false;}

    // Calcular Dígito Verificador
    suma = 0;
    multiplo = 2;

    // Para cada dígito del Cuerpo
    for(i=1;i<=cuerpo.length;i++) {

        // Obtener su Producto con el Múltiplo Correspondiente
        index = multiplo * valor.charAt(cuerpo.length - i);

        // Sumar al Contador General
        suma = suma + index;

        // Consolidar Múltiplo dentro del rango [2,7]
        if(multiplo < 7) { multiplo = multiplo + 1; } else { multiplo = 2; }

    }

    // Calcular Dígito Verificador en base al Módulo 11
    dvEsperado = 11 - (suma % 11);

    // Casos Especiales (0 y K)
    dv = (dv == 'K')?10:dv;
    dv = (dv == 0)?11:dv;

    // Validar que el Cuerpo coincide con su Dígito Verificador
    if(dvEsperado != dv) {
    	rut.setCustomValidity("RUT Inválido");
    	return false;
    }


    // Si todo sale bien, eliminar errores (decretar que es válido)
    rut.setCustomValidity('');
}
</script>
{% endblock %}

blog/templates/blog/gracias.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        <br>
        <h7>Gracias por tu respuesta</h7>
        <button class="btn btn-info btn-volver"><a href="/">Volver a formulario</a></button>
        <br>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        {% if user.is_authenticated %}
            <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
{% for post in posts %}
    <div class="post">
        <div class="date">
            <p>published: {{ post.published_date }}</p>
        </div>
        <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endfor %}
{% endblock %}

blog/templates/blog/validarRUT.html
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Validador de RUT HTML5</title>
</head>
<body>
    <form>
        <input type="text" id="rut" name="rut" required oninput="checkRut(this)" placeholder="Ingrese RUT">
        <button type="submit">Validar RUT y Enviar Form</button>
        <script src="validarRUT.js"></script>
    </form>
</body>
</html>